### PR TITLE
Gut HaskellDb down to primquery relation type

### PR DESCRIPTION
**Pull request by kanishka-azimi**
This compiles with stackage nightly-2017-03-30 with ghc-8.0.2, without any code changes except deletions. I didn't look into the ghc-8.0.1 build errors or try to fix them. (Issue #27)

If haskelldb is abandoned, it might make sense to publish this to hackage as haskelldb-primquery as a useful, simple starting point for future developers. 

Feel free to close this if you disagree.

### CODE REVIEW

**Comment by kanishka-azimi** [comment]
I might publish something like haskelldb-primquery to hackage myself, we'll see.

**Comment by tomjaguarpaw** [comment]
Would this provide much more benefit that Opaleye's PrimQuery type, which
itself is a tidied and extended version of HaskellDB's?

**Comment by kanishka-azimi** [comment]
Not really, but if the choice is between people not using haskelldb at all because it has rotted or some part of it living on, I think it makes more sense to publish the part that hasn't rotted.

For Hackage as a whole, the most valuable action that aligns with what I need right now would be to split off Opaleye's primquery into its own library. I had very little time at work to get going, so I used PrimQuery because it took me no time to understand. I assume another hour or two, and I can move my work over to opaleye's primquery, but I will not be using Opaleye proper for quite a long time.

We have talked a bit on reddit. We left it off that you encouraged my writing a backend for mysql. I can contribute to pieces of that, but I can't produce a fully functioning backend for others to use.

**Comment by tomjaguarpaw** [comment]
Ah that's right, I remember.  Good luck with your project.

**Comment by kanishka-azimi** [comment]
@tomjaguarpaw ready to attempt to convert to using opaleye's primquery. Would you be willing to break off opaleye-primquery as a separate hackage project? I will continue this discussion in opaleye repo.

**Pull request closed without merging**
